//html网页
const char* Root_Html={"<!DOCTYPE html>"
"<html lang=\"en\">"
"<head>"
    "<meta charset=\"UTF-8\">"
    "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">"
    "<title>Wifi 配网</title>"
"</head>"
"<style type=\"text/css\">.input{display: block; margin-top: 10px;}.input span{width: 100px; float: left; float: left; height: 36px; line-height: 36px;}.input input{height: 30px;width: 200px;}.btn{width: 120px; height: 35px; background-color: #10b462; border:0px; color:#ffffff; margin-top:15px; margin-left:100px;}</style>"
"<body>"
    "<h2 style=\"color: rgb(218, 90, 32);padding-left: 87px;\">Wifi配网页面</h2>"
    "<br/>"
    "<form method=\"POST\" action=\"connect\">"
        "<label class=\"input\">"
          "<span>Wifi名称:</span>"
          "<input type=\"text\" name=\"ssid\">"
        "</label>"
        "<br/>"
        "<label class=\"input\">"
          "<span>WiFi密码:</span>"
          "<input type=\"text\" name=\"password\">"
        "</label>"
        "<br/>"
        "<input class=\"btn\" type=\"submit\" name=\"submit\" value=\"保存\">"
    "</form>"
"</body>"
"</html>"};

 const char* Submit_Html="<html><body><h1>Successful!<br />保存成功!<br />ESP32正在连接WIFI中·······<br />您可以关闭当前页面等待连接.</h1></body></html>";